# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiritbuzz', '0005_auto_20160628_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/products/main/generic-liquor-bottle.jpeg', upload_to='images/products/main'),
        ),
    ]
