# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiritbuzz', '0006_auto_20160628_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productview',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductView',
        ),
    ]
